name: Build kernel (gcc)

on:
  workflow_dispatch:

env:
  Kernel_Link: https://github.com/samsungexynos7870/android_kernel_samsung_exynos7870 -b twrp
  GCC: https://github.com/adekmaulana/aarch64-linux-android
  
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
                               
       - name: Build
         run: |
              sudo apt update && sudo apt install git wget make zip -y
              cd && git clone --depth=1 $Kernel_Link kernel
              git clone --depth=1 $GCC /opt/gcc && gcc1=/opt/gcc/bin/aarch64-linux-android-
              cd && cd kernel && sed -i '4s/.*/export CROSS_COMPILE= $gcc1/' build_kernel.sh
              bash *.sh
              ls arch/arm64/boot
              zip -r kernel.zip arch/arm64/boot/Image
              
       - name: Save
         uses: actions/upload-artifact@v3
         with:
            name: kernel.zip
            path: /home/runner/kernel/kernel.zip
            retention-days: 5
