name: Build kernel (gcc)

on:
  workflow_dispatch:

env:
  Kernel_Link: https://github.com/n7105/android_kernel_samsung_m10lte
  GCC: https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9
  
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
                               
       - name: Build
         run: |
              sudo apt update && sudo apt install git wget make ccache zip -y
              cd && git clone --depth=1 $Kernel_Link kernel && cd kernel
              git clone --depth=1 $GCC /opt/gcc
              export ANDROID_MAJOR_VERSION=q && bash b*.sh
              ls arch/arm64/boot
              zip -r kernel.zip arch/arm64/boot/Image
              
       - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: workspace/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/${{ github.event.inputs.BUILD_TARGET }}.img
        name: ${{ github.event.inputs.DEVICE_NAME }}-${{ github.run_id }}
        tag_name: ${{ github.run_id }}
        body: |
          Manifest: ${{ github.event.inputs.MANIFEST_BRANCH }}
          Device: ${{ github.event.inputs.DEVICE_NAME }}
          Target: ${{ github.event.inputs.BUILD_TARGET }}.img
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
