name: Build kernel (gcc)

on:
  workflow_dispatch:

env:
  Kernel_Link: https://github.com/n7105/android_kernel_samsung_m10lte
  GCC: https://github.com/adekmaulana/aarch64-linux-android
  
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
                               
       - name: Build
         run: |
              sudo apt update && sudo apt install git wget make ccache zip -y
              cd && git clone --depth=1 $Kernel_Link kernel && cd kernel
              git clone --depth=1 $GCC /opt/gcc
              export ANDROID_MAJOR_VERSION=q && bash b*.sh
              ls arch/arm64/boot
              zip -r kernel.zip arch/arm64/boot/Image
              
       - name: Save
         uses: actions/upload-artifact@v3
         with:
            name: kernel.zip
            path: /home/runner/kernel/kernel.zip
            retention-days: 5
