name: Download

on:
  workflow_dispatch:
    inputs:
      LINK: 
        description: 'link'
        required: true
        default: ''

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
                               
       - name: Dump
         run: |
              sudo apt update -y && sudo apt install aria2 wget -y
              mkdir download && cd download && aria2c -o file.zip ${{ github.event.inputs.LINK }}
              
       - name: Save
         uses: softprops/action-gh-release@v1
         with:
           files: /home/runner/work/my_tools/my_tools/download/file.zip               
           name: Downloaded file
           tag_name: ${{ github.run_id }}                    
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
