name: Dump (samsung)

on:
  workflow_dispatch:
    inputs:
      LINK: 
        description: 'firmware link'
        required: true
        default: ''
      Part: 
        description: 'Partition (boot/system/recovery/...)'
        required: true
        default: ''

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
                               
       - name: Dump
         run: |
              sudo apt update -y && sudo apt install tar wget zip unzip p7zip -y
              mkdir fw && cd fw && wget -c ${{ github.event.inputs.LINK }}
              7za -y x *
              7za -y x "*.tar*"
              7za -y x ${{ github.event.inputs.PART }}*
              
       - name: Save
         uses: softprops/action-gh-release@v1
         with:
           files: /home/runner/work/my_tools/my_tools/fw/${{ github.event.inputs.PART }}.img                
           name: ${{ github.event.inputs.PART }}
           tag_name: ${{ github.run_id }}                    
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
